// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"execution-service/execution"
	"execution-service/instance"
	"execution-service/model"
	"execution-service/proof"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from main.go:

func InitializeInstanceController() instance.InstanceController {
	instanceService := instance.NewInstanceService()
	instanceController := instance.NewInstanceController(instanceService)
	return instanceController
}

func InitializeModelController() model.ModelController {
	modelService := model.NewModelService()
	modelController := model.NewModelController(modelService)
	return modelController
}

func InitializeExecutionController() execution.ExecutionController {
	executionService := execution.InitializeExecutionService()
	executionController := execution.NewExecutionController(executionService)
	return executionController
}

func InitializeProofController() proof.ProofController {
	proofService := proof.InitializeProofService()
	proofController := proof.NewProofController(proofService)
	return proofController
}

// main.go:

var instanceProviders = wire.NewSet(instance.NewInstanceController, instance.NewInstanceService)

var modelProviders = wire.NewSet(model.NewModelController, model.NewModelService)

var executionProviders = wire.NewSet(execution.NewExecutionController, execution.InitializeExecutionService)

var proofProviders = wire.NewSet(proof.NewProofController, proof.InitializeProofService)

func main() {

	instanceController := InitializeInstanceController()
	modelController := InitializeModelController()
	executionController := InitializeExecutionController()
	proofController := InitializeProofController()

	router := gin.Default()
	router.POST("/models", modelController.CreateModel)

	router.GET("/models/:modelId", modelController.FindModelById)
	router.GET("/models/choreography/:choreographyId", modelController.FindModelsByChoreography)
	router.PUT("/models", modelController.ImportModel)

	router.GET("/instances/:instanceId", instanceController.FindInstanceById)
	router.GET("/instances/model/:modelId/", instanceController.FindInstancesByModel)
	router.PUT("/instances", instanceController.ImportInstance)

	router.POST("/instances/instantiation", executionController.InstantiateModel)
	router.POST("/instances/transition", executionController.ExecuteTransition)

	router.PUT("/proof/instantiation", proofController.ProveInstantiation)
	router.PUT("/proof/transition", proofController.ProveTransition)
	router.PUT("/proof/termination", proofController.ProveTermination)

	router.Run("localhost:8080")
}
