// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package execution

import (
	"execution-service/domain"
	"execution-service/instance"
	"execution-service/model"
)

// Injectors from execution_service.go:

func InitializeExecutionService(modelPort model.ModelPort) ExecutionService {
	instanceService := instance.NewInstanceService()
	modelService := model.NewModelService(modelPort)
	executionService := NewExecutionService(instanceService, modelService)
	return executionService
}

// execution_service.go:

type ExecutionService struct {
	InstanceService instance.InstanceService
	ModelService    model.ModelService
}

func NewExecutionService(instanceService instance.InstanceService, modelService model.ModelService) ExecutionService {
	return ExecutionService{
		InstanceService: instanceService,
		ModelService:    modelService,
	}
}

func (service *ExecutionService) InstantiateModel(cmd InstantiateModelCommand) (domain.Instance, error) {
	model2, err := service.ModelService.FindModelById(cmd.Model)
	if err != nil {
		return domain.Instance{}, err
	}
	instanceResult, err := model2.Instantiate(cmd.PublicKeys)
	if err != nil {
		return domain.Instance{}, err
	}
	service.InstanceService.SaveInstance(instanceResult)
	return instanceResult, nil
}

func (service *ExecutionService) ExecuteTransition(cmd ExecuteTransitionCommand) (domain.Instance, error) {
	model2, err := service.ModelService.FindModelById(cmd.Model)
	if err != nil {
		return domain.Instance{}, err
	}
	currentInstance, err := service.InstanceService.FindInstanceById(cmd.Instance)
	if err != nil {
		return domain.Instance{}, err
	}
	transition, err := model2.FindTransitionById(cmd.Transition)
	if err != nil {
		return domain.Instance{}, err
	}
	var nextInstance domain.Instance
	if len(cmd.Message) == 0 {
		nextInstance, err = currentInstance.ExecuteTransition(transition)
	} else {
		nextInstance, err = currentInstance.ExecuteTransitionWithMessage(transition, cmd.Message)
	}
	if err != nil {
		return domain.Instance{}, err
	}
	service.InstanceService.SaveInstance(nextInstance)
	return nextInstance, nil
}
