// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package signature

import (
	"execution-service/domain"
	"execution-service/utils"
	"github.com/consensys/gnark-crypto/hash"
)

// Injectors from signature_service.go:

func InitializeSignatureService() SignatureService {
	signatureParameters := NewSignatureParameters()
	signatureService := NewSignatureService(signatureParameters)
	return signatureService
}

// signature_service.go:

type SignatureService struct {
	signatureParameters SignatureParameters
}

func NewSignatureService(signatureParameters SignatureParameters) SignatureService {
	return SignatureService{
		signatureParameters: signatureParameters,
	}
}

func (service *SignatureService) Sign(instance domain.Instance) Signature {
	privateKey := service.signatureParameters.SignaturePrivateKey
	signature, err := privateKey.Sign(instance.Hash.Value[:], hash.MIMC_BN254.New())
	utils.PanicOnError(err)

	return Signature{
		Value:     signature,
		PublicKey: service.GetPublicKey(),
	}
}

func (service *SignatureService) GetPublicKey() domain.PublicKey {
	privateKey := service.signatureParameters.SignaturePrivateKey
	return domain.PublicKey{
		Value: privateKey.PublicKey.Bytes(),
	}
}
